//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudokolor.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudokolor.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game&apos;s code copied !.
        /// </summary>
        public static string app_page_jeu_confirmation {
            get {
                return ResourceManager.GetString("app_page_jeu_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sudokolor.
        /// </summary>
        public static string app_page_jeu_titre {
            get {
                return ResourceManager.GetString("app_page_jeu_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game&apos;s code.
        /// </summary>
        public static string app_page_jeu_txt_code_partie {
            get {
                return ResourceManager.GetString("app_page_jeu_txt_code_partie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string app_page_options_langue {
            get {
                return ResourceManager.GetString("app_page_options_langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart the application to update the language..
        /// </summary>
        public static string app_page_options_langue_changee {
            get {
                return ResourceManager.GetString("app_page_options_langue_changee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        public static string app_page_options_langue_defaut {
            get {
                return ResourceManager.GetString("app_page_options_langue_defaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a language.
        /// </summary>
        public static string app_page_options_langue_selection {
            get {
                return ResourceManager.GetString("app_page_options_langue_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string app_page_options_retour {
            get {
                return ResourceManager.GetString("app_page_options_retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display type.
        /// </summary>
        public static string app_page_options_theme {
            get {
                return ResourceManager.GetString("app_page_options_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numbers.
        /// </summary>
        public static string app_page_options_theme_chiffres {
            get {
                return ResourceManager.GetString("app_page_options_theme_chiffres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colorblind.
        /// </summary>
        public static string app_page_options_theme_daltonien {
            get {
                return ResourceManager.GetString("app_page_options_theme_daltonien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        public static string app_page_options_theme_defaut {
            get {
                return ResourceManager.GetString("app_page_options_theme_defaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a display type.
        /// </summary>
        public static string app_page_options_theme_selection {
            get {
                return ResourceManager.GetString("app_page_options_theme_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string app_page_options_titre {
            get {
                return ResourceManager.GetString("app_page_options_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string app_page_principale_abandon_cancel {
            get {
                return ResourceManager.GetString("app_page_principale_abandon_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abandon.
        /// </summary>
        public static string app_page_principale_abandon_confirm {
            get {
                return ResourceManager.GetString("app_page_principale_abandon_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abandon your current game?.
        /// </summary>
        public static string app_page_principale_abandon_popup {
            get {
                return ResourceManager.GetString("app_page_principale_abandon_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced.
        /// </summary>
        public static string app_page_principale_btn_avance {
            get {
                return ResourceManager.GetString("app_page_principale_btn_avance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classical game.
        /// </summary>
        public static string app_page_principale_btn_classique {
            get {
                return ResourceManager.GetString("app_page_principale_btn_classique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time trial.
        /// </summary>
        public static string app_page_principale_btn_contre_la_montre {
            get {
                return ResourceManager.GetString("app_page_principale_btn_contre_la_montre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beginner.
        /// </summary>
        public static string app_page_principale_btn_debutant {
            get {
                return ResourceManager.GetString("app_page_principale_btn_debutant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        public static string app_page_principale_btn_historique {
            get {
                return ResourceManager.GetString("app_page_principale_btn_historique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medium.
        /// </summary>
        public static string app_page_principale_btn_intermediaire {
            get {
                return ResourceManager.GetString("app_page_principale_btn_intermediaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New game.
        /// </summary>
        public static string app_page_principale_btn_nouvelle {
            get {
                return ResourceManager.GetString("app_page_principale_btn_nouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string app_page_principale_btn_options {
            get {
                return ResourceManager.GetString("app_page_principale_btn_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue game.
        /// </summary>
        public static string app_page_principale_btn_reprendre {
            get {
                return ResourceManager.GetString("app_page_principale_btn_reprendre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string app_page_principale_titre {
            get {
                return ResourceManager.GetString("app_page_principale_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are still some errors ! :(.
        /// </summary>
        public static string app_popup_grille_fausse {
            get {
                return ResourceManager.GetString("app_popup_grille_fausse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string app_popup_soumission_grille_btn_annuler {
            get {
                return ResourceManager.GetString("app_popup_soumission_grille_btn_annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit.
        /// </summary>
        public static string app_popup_soumission_grille_btn_soumettre {
            get {
                return ResourceManager.GetString("app_popup_soumission_grille_btn_soumettre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to submit the grid ?.
        /// </summary>
        public static string app_popup_soumission_grille_titre {
            get {
                return ResourceManager.GetString("app_popup_soumission_grille_titre", resourceCulture);
            }
        }
    }
}
